ALTER TABLE freshmart_trade.payment_orders
  MODIFY COLUMN provider VARCHAR(24) NOT NULL DEFAULT 'PERSONAL_WECHAT_QR',
  MODIFY COLUMN payment_mode VARCHAR(24) NOT NULL DEFAULT 'MANUAL_CONFIRMATION';
